version: '3'
services:
  ##GLUE##
  glue:
    container_name: "dipas_glue_nginx"
    image: nginx:1.21
    ports:
      - "8089:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - apache
  ##BACKEND##
  apache:
    container_name: "dipas_apache"
    image: bitnami/apache:2.4.41
    volumes:
      - ../repository:/app:delegated
      #- ../repository/.htaccess:/opt/bitnami/apache/conf/htaccess/.htaccess
      - ./apache/dipas_vhost.conf:/vhosts/my_vhost.conf:ro
      #- /app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - php
  php:
    container_name: "dipas_php"
    environment:
      PHP_IDE_CONFIG: serverName=phpdebug
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: ./php
      dockerfile: Dockerfile-php
    volumes:
      - ../repository:/app:delegated
      - ./php/php.ini:/opt/bitnami/php/etc/conf.d/php.ini:ro
      - ./php/pg.ini:/opt/bitnami/php/etc/conf.d/pg.ini:ro
    ports:
      - "2222:22"
  ##DATABASE##
  database:
    container_name: "dipas_postgres"
    image: postgres:13.4
    environment:
      POSTGRES_PASSWORD: dipas
      POSTGRES_DATABASE: dipas
      POSTGRES_USER: dipas
    ports:
      - "5432:5432"
    volumes:
      - ../database-postgre-13:/var/lib/postgresql/data:delegated
  database_frontend:
    container_name: "dipas_pgadmin"
    image: dpage/pgadmin4:5
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: dipas@gv.hamburg.de
      PGADMIN_DEFAULT_PASSWORD: dipas
  ##FRONTEND##
  dipas_vue:
    container_name: "dipas_vue"
    build:
      context: ../repository
      dockerfile: ../dockerd9/vue/Dockerfile-vue
    ports:
      - "8081:8080"
    volumes:
      - ../repository:/usr/src/app/
      - /usr/src/app/node_modules
  githook:
    build:
      context: ../repository
      dockerfile: ../dockerd9/githooks/Dockerfile.githooks
    volumes:
      - ../repository/.git:/tmp/.git
      - ../repository/hooks:/tmp/hooks
volumes:
  dipas_d8_data:
