<?php

/**
 * @file
 * Functions to support theming in the Dipas Admin theme.
 */

/**
 * Implements hook_preprocess_html().
 */

function dipas_admin_theme_preprocess_html(&$variables) {
  // Get currently active user and his roles.
  $account = \Drupal::currentUser();
  $roles = $account->getRoles();

  foreach ($roles as $role) {
    $variables['attributes']['class'][] = 'role-' . $role;
  }
}

